package fr.univnantes.termsuite.http;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

public class TermSuiteHttpSpec {
    @Test public void testGet() {
    }
}
